[project]
name = "system-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "mysqlclient==2.2.7",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
]
