# Generated by Django 5.2.7 on 2025-10-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('url', models.URLField()),
                ('is_ative', models.BooleanField(default=True)),
                ('jitter_sec', models.PositiveBigIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricsSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField()),
                ('timeslot_start', models.DateTimeField()),
                ('cpu_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('mem_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('uptime_sec', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_monitoring.machine')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
