# Generated by Django 5.2.7 on 2025-10-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitoring', '0002_rename_is_ative_machine_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cpu', 'CPU > 85%'), ('mem', 'Memory > 90% (30m)'), ('disk', 'Disk > 95% (2h)')], max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_timeslot', models.DateTimeField()),
                ('last_timeslot', models.DateTimeField()),
                ('details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_monitoring.machine')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['machine', 'type', 'active'], name='system_moni_machine_146859_idx')],
            },
        ),
    ]
