name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: "0"
      DJANGO_SETTINGS_MODULE: system_monitoring.settings
      SECRET_KEY: "ci-secret"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install project dependencies
        run: uv sync --dev

      - name: Django checks
        run: uv run python manage.py check -v 2

      - name: Ruff (lint + format check)
        run: |
          uv run ruff check
          uv run ruff format --check
